-- Initialize all databases
CREATE DATABASE IF NOT EXISTS db_auth;
CREATE DATABASE IF NOT EXISTS db_post;
CREATE DATABASE IF NOT EXISTS db_event;
CREATE DATABASE IF NOT EXISTS db_job;
CREATE DATABASE IF NOT EXISTS db_msg;
CREATE DATABASE IF NOT EXISTS db_resource;
